baseURL: "https://aviralgarg.com"
title: Aviral Garg
paginate: 5
theme: PaperMod
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Aviral Garg
  description: "Aviral Garg's website"
  author: Aviral Garg

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: false
  images: ["images/profile.jpg"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"
    favicon16x16: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"
    favicon32x32: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"
    apple_touch_icon: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"
    safari_pinned_tab: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"

  profileMode:
    enabled: true # needs to be explicitly set
    title: Aviral Garg
    subtitle: Software Engineer
    imageUrl: "https://github.com/gaviral/avi/blob/main/assets/images/profile.jpg?raw=true"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Aviral Garg
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags