baseURL: "https://aviralgarg.com"
title: Aviral Garg
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Aviral Garg
  description: "Aviral Garg's website"
  keywords: [Avi, Aviral, Garg, Aviral Garg, aviralgarg, aviralgarg.com, aviralgarg.github.io, aviralgarg.github.com]
  author: Aviral Garg
  images: ["https://aviralgarg.com/images/profile.jpg, https://aviralgarg.com/images/profile.jpg"]
  DateFormat: "Jan 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/profile.jpg"
    favicon16x16: "https://aviralgarg.com/images/profile.jpg"
    favicon32x32: "https://aviralgarg.com/images/profile.jpg"
    apple_touch_icon: "https://aviralgarg.com/images/profile.jpg"
    safari_pinned_tab: "https://aviralgarg.com/images/profile.jpg"

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    icon: "/images/profile.jpg"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Aviral Garg
    subtitle: Software Engineer
    imageUrl: "/images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Aviral Garg
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
